version: '3.8'

services:
  mongo-db:
    image: mongo:6.0.6
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME= ${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD= ${MONGO_PASS}
    volumes:
      - ./mongodb_data:/data/db
